fixed Dockercompose for initial build (#1)
arturshyshko/myplay pull request #2
Opened 2019-01-12 19:56 UTC by ArtemBernatskyy

2019-02-01 22:09 UTC, p1v2 requested changes
Please see my comments below

2019-02-01 22:09 UTC, p1v2 commented on README.md
> +змінити файл web/src/App.js , web/src/index.css
@ArtemBernatskyy , your Readme.md file doesn't look fine. It is written in Ukrainian language, but English language is preferable. Also it does not contain instructions about how to setup and run the project.

2019-02-01 22:09 UTC, p1v2 commented on client/web/Dockerfile
> +RUN mkdir /my-app
`/client` directory name will be more fine here

2019-02-01 22:09 UTC, p1v2 commented on client/web/src/App.js
> +            Ok, <code>src/App.js</code> here we have Ivan project
That is not only the Ivan project 😉

2019-02-01 22:09 UTC, p1v2 commented on server/myplay/bin/uwsgi.ini
> +workers = 0
Just lol

2019-02-01 22:09 UTC, p1v2 commented on server/myplay/core/models.py
> +# from django.conf import settings
Either uncomment and make sure it is working or delete this.

2019-02-02 15:29 UTC, ArtemBernatskyy commented on README.md
> +змінити файл web/src/App.js , web/src/index.css
:)))))) I've put it by mistake )))

2019-02-04 15:07 UTC, closed without merging

2019-02-04 15:08 UTC, ArtemBernatskyy commented on server/myplay/bin/uwsgi.ini
> +workers = 0
lol